version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: python ./src/infrastructure/django_framework/manage.py runserver 0.0.0.0:5000
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - ..:/app
      - /dev:/dev